### PR TITLE
Improved plot syntax

### PR DESCRIPTION
**Pull request by MigadaTang**

### CODE REVIEW

**Comment by jacintodavila** [comment]
Dear Wei, please advise. Do you want overwrite everything in the wuenic_extensions branch with what you have in the feature_render_new? I don't quite see how to solve the conflicts.

**Comment by MigadaTang** [comment]
> Dear Wei, please advise. Do you want overwrite everything in the wuenic_extensions branch with what you have in the feature_render_new? I don't quite see how to solve the conflicts.

Hi Jacinto, I think after merging the changes made on the main branch to wuenic_extension, which we already did, we only need to deal with a few commits I made to improve the plot syntax and scenario.

I have uploaded all the changes and tested a few examples. Hopefully, there are not many bugs left. Could you please help me review and test the code?

here is the commands to run the Rserve image

`docker run  --net=none --name=rserve rserve `

after that, just add `--volumes-from rserve` to the usual command that you've been using. This allows swish to talk to Rserve.

`docker run --volumes-from rserve -it -p 8082:3050 -v /Users/tang/swish_data:/data  -v /Users/tang/projects/LogicalEnglish:/app -e LOAD_KB=true  --memory="300m" logicalcontracts/swish-june2023
`

Not long ago, you told me that the swish image has been updated. I tried it today and most things are fine except that the tabling mechanism is not working on the swish-june2023 image. I'll try to figure it out later.

**Comment by MigadaTang** [comment]
I've uploaded a few examples to the LE website.

[the plot demo](https://logicalenglish.logicalcontracts.com/p/plot_demo.pl)  program is a simplified example to test the plot syntax.

[WUENIC](https://logicalenglish.logicalcontracts.com/p/WEI_WUENIC.pl) is the complete WUENIC program.

[sdn](https://logicalenglish.logicalcontracts.com/p/sdn.pl) is a scenario in a module

**Comment by jacintodavila** [comment]
I'll have a go.. soon. Thank you

**Comment by jacintodavila** [comment]
I don't have the rserve image locally available. Where did you get it from? 
 docker run  --net=none --name=rserve rserve 
Unable to find image 'rserve:latest' locally
docker: Error response from daemon: pull access denied for rserve, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by MigadaTang** [comment]
> I don't have the rserve image locally available. Where did you get it from? docker run --net=none --name=rserve rserve Unable to find image 'rserve:latest' locally docker: Error response from daemon: pull access denied for rserve, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I am using the swipl RServe image here https://hub.docker.com/r/swipl/rserve/

Can you try this command to pull the image ? 
`docker pull swipl/rserve`

**Comment by MigadaTang** [comment]
> 
Hello, Jacinto.

Are you able to get RServe up and running? A simple way to test the communication between RServe and Prolog is by running the r.version command in this SWISH tutorial. If it returns the version of R, then it is working.

Screenshot 2023-08-08 at 20 07 17

**Comment by jacintodavila** [comment]
All is running well!. We may need a notebook to show the way

wuenic-demo-tested

**Pull request merged**
