### PR TITLE
Feature arithmetic

### PR DESCRIPTION
**Pull request by MigadaTang**
Changes in this pull request include:
1. The introduction of arithmetic expressions with four operators +, -, *, /.
2. A complete removal of the previous expressions DCG, merge the previous date parsing into the new expressions DCG.
3. A change in the tokenizer package to stop it from recognizing the unary operators, such as '-' and '+'. By leaving them to Logical English, it is much easier to parse dates and unary operators. Since it is originally a different repo, I have to change it into a plain directory to submit my modification.
4. A temporary solution to parse 2022-02-06 as dates, not as an expression with two subtractions.

### CODE REVIEW

**Comment by MigadaTang** [comment]
Hi @jacintodavila , This feature is now ready to be merged. I have tested the change on multiple LE programs. Could you please help me check the code with some of your existing examples and see if they still work?

I would appreciate your consideration regarding the possibility of changing the tokenized submodule into a plain subdirectory. Given the limitation of not being able to modify the original repository, this approach seems to be the most feasible way for me to submit my modifications. I changed the built-in number predicate to make it ignore the unary operator before the numbers, so they can be handled by Logical English.
Screenshot 2023-06-05 at 18 11 31

**Comment by MigadaTang** [comment]
Hi @jacintodavila , Could you please help me delete the [LogicalContracts:feature_arithmetic](https://github.com/LogicalContracts/LogicalEnglish/tree/feature_arithmetic) branch and checkout a new branch from main? Because this branch is outdated and all the changes I want to make is on [MigadaTang:feature_arithmetic](https://github.com/MigadaTang/LogicalEnglish/tree/feature_arithmetic).

Or can we just merge [MigadaTang:feature_arithmetic](https://github.com/MigadaTang/LogicalEnglish/tree/feature_arithmetic) to your main branch without using [LogicalContracts:feature_arithmetic](https://github.com/LogicalContracts/LogicalEnglish/tree/feature_arithmetic) at all? However, I am not sure if you can access my branch this way.

**Comment by jacintodavila** [comment]
Dear @MigadaTang , please notice that [MigadaTang:feature_arithmetic](https://github.com/MigadaTang/LogicalEnglish/tree/feature_arithmetic) is your branch on your cloned LE repository. I can't access it except by answering your PR into the feature_arithmetic branch of the main repository (which you can´t access otherwise). So, now the two branches must be equal. I still see a comment that appear when running a query, which would have to be cleaned before I can merge into "my" main branch. Are you clear?

**Comment by MigadaTang** [comment]
Yes. These are already activated in my local branch. All we need right now is a new branch from your repo so I can push my latest code to that branch.

**Comment by jacintodavila** [comment]
OK @MigadaTang - Just created https://github.com/LogicalContracts/LogicalEnglish/tree/wuenic_extensions Let me know if you have any problem doing a PR on it.  Thank you

**Pull request merged**
